export const DeleteIcon = (props) => (
  <svg
    aria-hidden="true"
    fill="none"
    focusable="false"
    height="1.6em"
    role="presentation"
    viewBox="0 0 24 24"
    width="1.8em"
    {...props}
  >
    <circle
      cx="12"
      cy="12"
      r="10"
      stroke="currentColor"
      strokeWidth={1.5}
    />
    <line
      x1="8"
      y1="8"
      x2="16"
      y2="16"
      stroke="currentColor"
      strokeLinecap="round"
      strokeWidth={1.5}
    />
    <line
      x1="8"
      y1="16"
      x2="16"
      y2="8"
      stroke="currentColor"
      strokeLinecap="round"
      strokeWidth={1.5}
    />
  </svg>
);
