CREATE TABLE `CARRO` (
	`CodigoCarro` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Nombre` VARCHAR(255) NOT NULL,
	`Marca` VARCHAR(255) NOT NULL,
	`Modelo` VARCHAR(255) NOT NULL,
	`Anio` INTEGER NOT NULL,
    Descripcion varchar(750) NOT NULL,
	`PrecioCliente` INTEGER NOT NULL,
	`PrecioEstimado` NUMERIC NOT NULL,
	`Propietario` INTEGER NOT NULL,
	`Disponible` BIT NOT NULL,
	`Rentado` BIT,
	PRIMARY KEY(`CodigoCarro`)
);


CREATE TABLE `USUARIO` (
	`CodigoUsuario` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Nombre` VARCHAR(255) NOT NULL,
	`Apellido` VARCHAR(255) NOT NULL,
	`Correo` VARCHAR(255) NOT NULL,
	`Contrasena` VARCHAR(255) NOT NULL,
	`CodigoTipoUsuario` INTEGER NOT NULL,
	PRIMARY KEY(`CodigoUsuario`, `CodigoTipoUsuario`)
);
ALTER TABLE `USUARIO`
ADD COLUMN `Imagen` VARCHAR(755);


CREATE TABLE `TIPOUSUARIO` (
	`CodigoTipoUsuario` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Nombre` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`CodigoTipoUsuario`)
);


CREATE TABLE `BITACORARENTA` (
	`CodigoBitacoraRenta` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`CodigoCarro` INTEGER NOT NULL,
	`CodigoUsuarioRenta` INTEGER NOT NULL,
	`FechaInicio` DATETIME NOT NULL,
	`FechaFin` DATETIME NOT NULL,
	PRIMARY KEY(`CodigoBitacoraRenta`)
);


CREATE TABLE `SOLICITUDRENTA` (
	`CodigoSolicitudrenta` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`CodigoUsuarioSolicitante` INTEGER NOT NULL,
	`CodigoCarro` INTEGER NOT NULL,
	`FechaSolicitudRenta` DATETIME NOT NULL,
	`FechaRespuesta` DATETIME,
	PRIMARY KEY(`CodigoSolicitudrenta`)
);


CREATE TABLE `ImagenCarro` (
    `CodigoImagenCarro` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    `url` VARCHAR(255) NOT NULL,
    `CodigoCarro` INTEGER NOT NULL,
	`IdImagen` VARCHAR(255) NOT NULL,
    PRIMARY KEY(`CodigoImagenCarro`)
);


CREATE TABLE `Reserva` (
    `CodigoReserva` INTEGER NOT NULL AUTO_INCREMENT,
    `CodigoUsuarioSolicita` INTEGER NOT NULL,
    `CodigoCarro` INTEGER NOT NULL,
    `FechaSolicitud` DATETIME,
    `FechaRespuesta` DATETIME,
    `Aprobado` INTEGER,
    PRIMARY KEY(`CodigoReserva`)
);


ALTER TABLE `CARRO`
ADD FOREIGN KEY(`Propietario`) REFERENCES `CLIENTE`(`CodigoUsuario`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `CLIENTE`
ADD FOREIGN KEY(`CodigoTipoUsuario`) REFERENCES `TIPOUSUARIO`(`CodigoTipoUsuario`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `BITACORARENTA`
ADD FOREIGN KEY(`CodigoCarro`) REFERENCES `CARRO`(`CodigoCarro`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `BITACORARENTA`
ADD FOREIGN KEY(`CodigoUsuarioRenta`) REFERENCES `CLIENTE`(`CodigoUsuario`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SOLICITUDRENTA`
ADD FOREIGN KEY(`CodigoUsuarioSolicitante`) REFERENCES `CLIENTE`(`CodigoUsuario`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `SOLICITUDRENTA`
ADD FOREIGN KEY(`CodigoCarro`) REFERENCES `CARRO`(`CodigoCarro`)
ON UPDATE NO ACTION ON DELETE NO ACTION;